%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.21.0 on {{2018,7,25},{10,47,39}}

-ifndef(my_app_v4_sample_type).
-define(my_app_v4_sample_type, true).

-define(my_app_v4_sample_type_gpb_version, "3.21.0").

-ifndef('MY_APP_V4.SAMPLE.TYPE.FACTRESP_PB_H').
-define('MY_APP_V4.SAMPLE.TYPE.FACTRESP_PB_H', true).
-record('my_app_v4.sample.type.FactResp',
        {y                              % = 1, int32
        }).
-endif.

-endif.
