%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.21.0 on {{2018,7,25},{10,8,55}}

-ifndef(my_app_v4_sample_func).
-define(my_app_v4_sample_func, true).

-define(my_app_v4_sample_func_gpb_version, "3.21.0").

-ifndef('MY_APP_V4.SAMPLE.TYPE.FACTRESP_PB_H').
-define('MY_APP_V4.SAMPLE.TYPE.FACTRESP_PB_H', true).
-record('my_app_v4.sample.type.FactResp',
        {y                              % = 1, int32
        }).
-endif.

-ifndef('MY_APP_V4.SAMPLE.FUNC.FACT_PB_H').
-define('MY_APP_V4.SAMPLE.FUNC.FACT_PB_H', true).
-record('my_app_v4.sample.func.Fact',
        {x                              % = 1, int32
        }).
-endif.

-endif.
